app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    link-last-check-interval: 30s

  client:
    gitHub: "https://api.github.com"
    stackOverflow: "https://api.stackexchange.com/2.3"
    bot: ${BOT_URL:http://localhost:8090}

  debug-information:
    api-error-response-stack-trace-list-length: 5

  database-access-type: jpa

  retry:
    max-attempts: 3
    retry-status-codes: 500, 502, 503, 504
    type: linear
    delay-config:
      constant:
        back-off-period-millis: 1000
      linear:
        initial-interval-millis: 1000
        max-interval-millis: 5000
      exponential:
        initial-interval-millis: 1000
        multiplier: 2
        max-interval-millis: 100000

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: scrapper
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
    url: ${DB_URL:jdbc:postgresql://localhost:5432/scrapper}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:changeme}
  liquibase:
    enabled: false

server:
  port: 8080
# http://localhost:8080/swagger-ui/index.html
logging:
  config: classpath:log4j2-plain.xml
  level:
    org.springframework.jdbc.core: DEBUG
