app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  client:
    gitHub: "https://api.github.com"
    stackOverflow: "https://api.stackexchange.com/2.3"
    bot: ${BOT_URL:http://localhost:8090}

spring:
  application:
    name: scrapper
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/scrapper}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: false

server:
  port: 8080
# http://localhost:8080/swagger-ui/index.html
logging:
  config: classpath:log4j2-plain.xml
